name: account_demo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  delayed_display: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/ic_alert.png
    - assets/bank_logo.png

  fonts:
    - family: Commissioner
      fonts:
        - asset: fonts/Commissioner-Regular.ttf
          weight: 400
        - asset: fonts/Commissioner-Bold.ttf
          weight: 600
        - asset: fonts/Commissioner-Medium.ttf
          weight: 500
        - asset: fonts/Commissioner-Black.ttf
          weight: 700
